apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - list:
        elements:
          - name: cert-manager
            namespace: cert-manager
            chartRepo: https://charts.jetstack.io
            chart: cert-manager
            targetRevision: v1.21.1
            wave: "-20"
            path: cert-manager/manifests
          - name: external-secrets
            namespace: external-secrets
            chartRepo: https://charts.external-secrets.io
            chart: external-secrets
            targetRevision: 2.10.0
            wave: "-10"
            path: external-secrets/manifests
          - name: vault
            namespace: vault
            chartRepo: https://helm.releases.hashicorp.com
            chart: vault
            targetRevision: 0.34.1
            wave: "0"
            path: vault/manifests
  template:
    metadata:
      name: '{{.name}}-dev'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: '{{.wave}}'
    spec:
      project: default
      sources:
        - repoURL: '{{.chartRepo}}'
          chart: '{{.chart}}'
          targetRevision: '{{.targetRevision}}'
          helm:
            releaseName: '{{.name}}'
            valueFiles:
              - '$values/infrastructure/{{.name}}/values-base.yaml'
              - '$values/envs/dev/{{.name}}.yaml'
        - repoURL: "{{GIT_REPO_URL}}"
          targetRevision: {{GIT_TARGET_BRANCH}}
          ref: values
        - repoURL: "{{GIT_REPO_URL}}"
          targetRevision: {{GIT_TARGET_BRANCH}}
          path: infrastructure/{{.path}}
          directory:
            recurse: true
      ignoreDifferences:
        - group: apiextensions.k8s.io
          kind: CustomResourceDefinition
          jqPathExpressions:
            - .spec.versions[].schema
            - .status
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
