apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-root-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
spec:
  project: default
  source:
    repoURL: "{{GIT_REPO_URL}}"
    targetRevision: main
    path: argocd
    directory:
      include: "{apps-prod}.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
